/**
 * Global constants and configuration
 */
export declare const MBITE_DECIMAL_PLACES = 8n;
export declare const SMALLEST_UNIT_PER_MBITE: bigint;
export declare const PLATFORM_FEE_BASIS_POINTS = 200n;
export declare const DEFAULT_CONFIRMATIONS_REQUIRED = 2;
export declare const CHECKOUT_EXPIRY_MINUTES = 15;
export declare const DOWNLOAD_URL_TTL_HOURS = 24;
export declare const DOWNLOAD_URL_TTL_MS: number;
export declare const DOWNLOADS_PER_IP_PER_DAY = 5;
export declare const JWT_ALGORITHM = "HS256";
export declare const JWT_EXPIRY_MINUTES = 15;
export declare const REFRESH_TOKEN_EXPIRY_DAYS = 7;
export declare const REFRESH_TOKEN_REUSE_DETECTION_ENABLED = true;
export declare const RATE_LIMIT_AUTH_WINDOW_MS: number;
export declare const RATE_LIMIT_AUTH_MAX = 10;
export declare const RATE_LIMIT_API_WINDOW_MS: number;
export declare const RATE_LIMIT_API_MAX = 100;
export declare const WEBHOOK_RETRY_INTERVALS_MS: number[];
export declare const WEBHOOK_MAX_RETRIES = 5;
export declare const WEBHOOK_TIMEOUT_MS: number;
export declare const MAX_FILE_SIZE_BYTES: bigint;
export declare const UPLOAD_CHUNK_SIZE_BYTES: number;
export declare const ALLOWED_MIMETYPES: string[];
export declare const SOFT_DELETE_ENABLED = true;
export declare const AUDIT_LOG_ENABLED = true;
export declare const ENCRYPTION_ALGORITHM = "aes-256-gcm";
export declare const ENCRYPTION_KEY_SIZE_BYTES = 32;
export declare const ENCRYPTION_IV_SIZE_BYTES = 12;
export declare const ENCRYPTION_AUTH_TAG_SIZE_BYTES = 16;
export declare const DEFAULT_PAGE = 1;
export declare const DEFAULT_LIMIT = 20;
export declare const MAX_LIMIT = 100;
export declare const PRODUCT_CATEGORIES: readonly ["SOFTWARE", "EBOOK", "ART", "COURSE", "OTHER"];
export declare const DOWNLOAD_LIMITS: readonly ["1", "3", "UNLIMITED"];
export declare const STORE_SLUG_MIN_LENGTH = 2;
export declare const STORE_SLUG_MAX_LENGTH = 50;
export declare const STORE_NAME_MIN_LENGTH = 2;
export declare const STORE_NAME_MAX_LENGTH = 100;
export declare const ERROR_CODES: {
    readonly INVALID_CREDENTIALS: "INVALID_CREDENTIALS";
    readonly EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED";
    readonly MFA_REQUIRED: "MFA_REQUIRED";
    readonly INVALID_MFA_CODE: "INVALID_MFA_CODE";
    readonly UNAUTHORIZED: "UNAUTHORIZED";
    readonly TOKEN_EXPIRED: "TOKEN_EXPIRED";
    readonly TOKEN_INVALID: "TOKEN_INVALID";
    readonly VALIDATION_ERROR: "VALIDATION_ERROR";
    readonly INVALID_REQUEST: "INVALID_REQUEST";
    readonly DUPLICATE_EMAIL: "DUPLICATE_EMAIL";
    readonly DUPLICATE_SLUG: "DUPLICATE_SLUG";
    readonly INVALID_WALLET_ADDRESS: "INVALID_WALLET_ADDRESS";
    readonly INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE";
    readonly NOT_FOUND: "NOT_FOUND";
    readonly MERCHANT_NOT_FOUND: "MERCHANT_NOT_FOUND";
    readonly STORE_NOT_FOUND: "STORE_NOT_FOUND";
    readonly PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND";
    readonly TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND";
    readonly FILE_NOT_FOUND: "FILE_NOT_FOUND";
    readonly DOWNLOAD_LIMIT_EXCEEDED: "DOWNLOAD_LIMIT_EXCEEDED";
    readonly IP_RATE_LIMIT_EXCEEDED: "IP_RATE_LIMIT_EXCEEDED";
    readonly COUPON_EXPIRED: "COUPON_EXPIRED";
    readonly COUPON_USAGE_LIMIT_EXCEEDED: "COUPON_USAGE_LIMIT_EXCEEDED";
    readonly STORE_SUSPENDED: "STORE_SUSPENDED";
    readonly PRODUCT_NOT_ACTIVE: "PRODUCT_NOT_ACTIVE";
    readonly PRODUCT_EXPIRED: "PRODUCT_EXPIRED";
    readonly TRANSACTION_EXPIRED: "TRANSACTION_EXPIRED";
    readonly PAYMENT_ALREADY_RECEIVED: "PAYMENT_ALREADY_RECEIVED";
    readonly IDEMPOTENCY_KEY_CONFLICT: "IDEMPOTENCY_KEY_CONFLICT";
    readonly WALLET_NOT_SET: "WALLET_NOT_SET";
    readonly INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR";
    readonly DATABASE_ERROR: "DATABASE_ERROR";
    readonly ENCRYPTION_ERROR: "ENCRYPTION_ERROR";
    readonly STORAGE_ERROR: "STORAGE_ERROR";
    readonly WEBHOOK_DELIVERY_FAILED: "WEBHOOK_DELIVERY_FAILED";
};
export declare const HTTP_STATUS: {
    readonly OK: 200;
    readonly CREATED: 201;
    readonly ACCEPTED: 202;
    readonly BAD_REQUEST: 400;
    readonly UNAUTHORIZED: 401;
    readonly FORBIDDEN: 403;
    readonly NOT_FOUND: 404;
    readonly CONFLICT: 409;
    readonly UNPROCESSABLE_ENTITY: 422;
    readonly TOO_MANY_REQUESTS: 429;
    readonly INTERNAL_SERVER_ERROR: 500;
    readonly SERVICE_UNAVAILABLE: 503;
};
export declare const WEBHOOK_EVENTS: readonly ["payment.received", "file.downloaded", "payout.completed"];
export declare const API_KEY_PUBLIC_PREFIX_LIVE = "pk_live_";
export declare const API_KEY_PUBLIC_PREFIX_TEST = "pk_test_";
export declare const API_KEY_SECRET_PREFIX_LIVE = "sk_live_";
export declare const API_KEY_SECRET_PREFIX_TEST = "sk_test_";
export declare const ENV_PROD = "production";
export declare const ENV_STAGING = "staging";
export declare const ENV_DEV = "development";
export declare const ENV_TEST = "test";
//# sourceMappingURL=constants.d.ts.map